# Default HTTP Server Configuration

Server {

	# Basic server settings
	server_name defaultServer;
	listen 128.0.0.1:8080;
	listen 128.0.0:8080;						# not enough parts of IP
	listen 128.0.0.1.1:8080;					# too many parts of IP
	listen 128.0.256.1:8080;					# too big number
	listen 128.0.1343.1:8080;					# too many digits
	listen 128.0.034.1:8080;					# leading zeroes
	listen 128.0..1:8080;						# empty part
	client_max_body_size 10m;
	root /server_files;

	# Error pages
	error_page 400 ./www/errorPages/400.html;
	error_page 404 ./www/errorPages/404.html;
	error_page 500 ./www/errorPages/500.htm;	# file doesn't exist
	error_page 4520 /error_pages/4520.html; 	# wrong errorpage code

	# Static file serving
	location / {
		root /server_files/www;
		index index.html ;
		allowed_methods GET POST;
		autoindex off;
	}

	# Images directory with autoindex enabled
	location /images {
		root /server_files/images;
		allowed_methods GET;					# what should happen if we have duplicate methods
		autoindex on;
	}

	# Location that supports uploads
	location /upload {
		root /server_files/uploads;
		allowed_methods POST;
		upload_dir /server_files/uploads;
		client_max_body_size 50m;
	}

	# CGI example (for PHP)
	location /php {
		root /server_files/cgi-bin;
		allowed_methods GET POST;
		cgi_ext .php;
	}

	# Redirect old paths
	location /oldsite {
		return 301 /;
	}
}
